[webservers]
web-01 ansible_connection=local
web-02 ansible_connection=local

[databases]
db-01 ansible_connection=local
db-02 ansible_connection=local

[development:children]
webservers

[staging:children]
webservers
databases

[production:children]
webservers
databases
