---
- name: Variable Debugging Example
  hosts: webservers
  gather_facts: yes

  vars:
    custom_message: "Hello from Ansible"

  tasks:

    - debug:
        msg: "Custom message is: {{ custom_message }}"

    - debug:
        var: ansible_distribution

    - debug:
        msg: "Hostname: {{ inventory_hostname }}"
