---
firewall_zone: public

firewall_services:
  - ssh
  - http
  - https

firewall_ports:
  - 8080/tcp
  - 8443/tcp

firewall_rich_rules:
  - 'rule family="ipv4" source address="10.0.0.0/8" service name="ssh" accept'
