---
- name: Final Verification
  hosts: webservers
  become: yes

  tasks:
    - service_facts:

    - assert:
        that:
          - ansible_facts.services['httpd.service'].state == 'running'

    - uri:
        url: http://127.0.0.1
        status_code: 200
