all:
  children:
    webservers:
      hosts:
        localhost:
    databases:
      hosts:
        localhost:
    loadbalancers:
      hosts:
        localhost:
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
